#ifndef OPTION_SCREENS_H
#define OPTION_SCREENS_H

#define OPTION_FLAGS_SHIFT_EASY_SLEEP     0
#define OPTION_FLAGS_SHIFT_RUMBLE_FEATURE 1
#define OPTION_FLAGS_SHIFT_AUTO_FEATURE   2

#define OPTION_FLAGS_EASY_SLEEP     (1 << OPTION_FLAGS_SHIFT_EASY_SLEEP)
#define OPTION_FLAGS_RUMBLE_FEATURE (1 << OPTION_FLAGS_SHIFT_RUMBLE_FEATURE)
#define OPTION_FLAGS_AUTO_FEATURE   (1 << OPTION_FLAGS_SHIFT_AUTO_FEATURE)

enum OptionScreenStates {
    OPTS_STATE_FADE_IN = 0,
    OPTS_STATE_SELECT_OPTION,
    OPTS_STATE_EASY_SLEEP_CONFIRMATION,
    OPTS_STATE_RUMBLE_FEATURE_CONFIRMATION,
    OPTS_STATE_AUTO_SLEEP_CONFIRMATION,
    OPTS_STATE_SAVE_ERROR,
    OPTS_STATE_SAVE_ERROR_CONFIRMATION,
    OPTS_STATE_LEAVE,
};

#endif