#ifndef OPTION_SCREENS_H
#define OPTION_SCREENS_H

enum OptionScreenStates {
    OPTS_STATE_FADE_IN = 0,
    OPTS_STATE_SELECT_OPTION,
    OPTS_STATE_EASY_SLEEP_CONFIRMATION,
    OPTS_STATE_RUMBLE_FEATURE_CONFIRMATION,
    OPTS_STATE_AUTO_SLEEP_CONFIRMATION,
    OPTS_STATE_SAVE_ERROR,
    OPTS_STATE_SAVE_ERROR_CONFIRMATION,
    OPTS_STATE_LEAVE,
};

#endif